-- AlterTable
ALTER TABLE `event` ADD COLUMN `createdBy` INTEGER NULL;

-- AlterTable
ALTER TABLE `match` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NULL;
